livox_lidar_publisher:
  ros__parameters:
    xfer_format: 2
    multi_topic: 0
    data_src: 0
    publish_freq: 10.0
    output_type: 1
    frame_id: 'mid360_link'
    user_config_path: '$(find-pkg-share unitree_bringup)/config/mid360_config.json'
